name: Mirror Private to Public Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Push to public repo
      env:
        PUBLIC_REPO: https://${{ secrets.SYNC_TOKEN }}@github.com/glitched-nx/Blue_Edition_2__RCM_V1.git
      run: |
        git remote set-url --push origin $PUBLIC_REPO
        git push origin main      