name: Trigger Sync

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sync Action
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CSYNC_TOKEN }}
          repository: glitched-nx/Blue_Edition_2__RCM_V1
          event-type: sync-main
